In [7]:
import pandas as pd

input_file = "data/train_preprocessed/admissions_train_modified_ML.csv"
output_file = "data/admissions_train_modified_cleaned.csv"

df = pd.read_csv(input_file)

columns_to_remove = ["subject_id", "admittime", "dischtime", "deathtime", "race", "hospital_expire_flag"]

df_cleaned = df.drop(columns=columns_to_remove)

df_cleaned.to_csv(output_file, index=False)

print(f"Columns {columns_to_remove} have been removed and saved to {output_file}.")

Columns ['subject_id', 'admittime', 'dischtime', 'deathtime', 'race', 'hospital_expire_flag'] have been removed and saved to data/admissions_train_modified_cleaned.csv.

In [32]:
import pandas as pd

admissions_file = "data/admissions_train_modified_cleaned.csv"
average_amounts_file = "data/train_preprocessed/average_amounts_per_item_per_admission_input_filtered.csv"
average_amounts_file_2 = "data/train_preprocessed/average_amounts_per_item_per_admission_ingredient.csv"
procedure_counts_file = "data/train_preprocessed/procedure_count.csv"
average_values_chartevent_file = "data/train_preprocessed/average_values_per_item_per_admission_chartevent_filtered.csv"
average_values_output_file = "data/train_preprocessed/average_values_per_item_per_admission_output_filtered.csv"
# icustays_file = "data/train/icustays_train.csv"
icustays_aggregated_file = "data/train_preprocessed/icustays_aggregated.csv"

output_file = "data/merged_data_2378.csv"

admissions = pd.read_csv(admissions_file)
average_amounts = pd.read_csv(average_amounts_file)
average_amounts_2 = pd.read_csv(average_amounts_file_2)
procedure_counts = pd.read_csv(procedure_counts_file)
average_values_chartevent = pd.read_csv(average_values_chartevent_file)
average_values_output = pd.read_csv(average_values_output_file)
icustays_aggregated = pd.read_csv(icustays_aggregated_file)

merged_data = admissions
merged_data = pd.merge(merged_data, icustays_aggregated, on="hadm_id", how="inner")
merged_data = pd.merge(merged_data, average_amounts, on="hadm_id", how="outer")
merged_data = pd.merge(merged_data, average_amounts_2, on="hadm_id", how="outer")
merged_data = pd.merge(merged_data, procedure_counts, on="hadm_id", how="outer")
merged_data = pd.merge(merged_data, average_values_chartevent, on="hadm_id", how="outer")
merged_data = pd.merge(merged_data, average_values_output, on="hadm_id", how="outer")
# 검토 필요

# 결측치 처리
merged_data = merged_data.fillna(-1)  # 결측치를 0으로 채움


merged_data.to_csv(output_file, index=False)

print(f"Merged data has been saved to {output_file}.")
merged_data

Merged data has been saved to data/merged_data_2378.csv.

,hadm_id,within_120hr_death,los,Albumin 25%_average_amount,Albumin 5%_average_amount,Dextrose 5%_average_amount,Dextrose 10%_average_amount,Dextrose 50%_average_amount,Fresh Frozen Plasma_average_amount,Sodium Bicarbonate 8.4%_average_amount,...,PACU Urine_average_value,Cath Lab_average_value,Pre-Admission_average_value,GU Irrigant Volume In_average_value,GU Irrigant/Urine Volume Out_average_value,TF Residual_average_value,TF Residual Output_average_value,Drainage Bag_average_value,Chest Tube #3_average_value,Chest Tube #4_average_value
0,20010074,0,2.589410,-1.0,-1.000000,161.946916,-1.0,-1.0,-1.0,-1.000,...,880.0,-1.0,-1.0,-1.0,-1.0,-1.000000,-1.0,-1.0,-1.0,-1.0
1,20011505,0,5.108530,-1.0,-1.000000,161.364454,-1.0,-1.0,-1.0,73.875,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.000000,-1.0,-1.0,-1.0,-1.0
2,20014219,0,19.133669,-1.0,-1.000000,85.109727,-1.0,-1.0,-1.0,-1.000,...,-1.0,-1.0,-1.0,-1.0,-1.0,26.571429,1000.0,-1.0,-1.0,-1.0
3,20020562,0,3.671887,-1.0,499.999981,96.693463,100.5,50.0,532.5,150.000,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.000000,-1.0,-1.0,-1.0,-1.0
4,20023734,0,0.793576,-1.0,-1.000000,133.333333,-1.0,-1.0,-1.0,-1.000,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.000000,-1.0,-1.0,-1.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2373,29964871,0,2.555000,-1.0,-1.000000,134.782609,-1.0,-1.0,-1.0,-1.000,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.000000,-1.0,-1.0,-1.0,-1.0
2374,29966638,0,10.394236,-1.0,-1.000000,100.000000,-1.0,-1.0,-1.0,-1.000,...,-1.0,-1.0,-1.0,-1.0,-1.0,68.684211,-1.0,-1.0,-1.0,-1.0
2375,29966688,0,1.570995,-1.0,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.000,...,-1.0,-1.0,2100.0,-1.0,-1.0,-1.000000,-1.0,-1.0,-1.0,-1.0
2376,29978132,0,7.429630,-1.0,-1.000000,123.057186,-1.0,-1.0,-1.0,-1.000,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.000000,-1.0,-1.0,-1.0,-1.0
2377,29995768,0,3.677245,-1.0,-1.000000,266.666669,-1.0,-1.0,-1.0,-1.000,...,-1.0,-1.0,1700.0,-1.0,-1.0,-1.000000,-1.0,-1.0,-1.0,-1.0

In [ ]:
# merged_data에 'race'가 있는지 확인

In [33]:
# merged_data의 hadm_id 개수 확인
print(f"merged_data: {len(merged_data['hadm_id'].unique())}")

merged_data: 2378

In [34]:
# subject_id, intime outtime 컬럼 제거후 csv 파일로 저장
output_file = "merged_data_cleaned.csv"
columns_to_remove = ["subject_id"]

merged_data_cleaned = merged_data.drop(columns=columns_to_remove)

merged_data_cleaned.to_csv(output_file, index=False)

print(f"Columns {columns_to_remove} have been removed and saved to {output_file}.")

merged_data_cleaned

KeyError: "['subject_id'] not found in axis"

# 데이터 분석

In [35]:
# 각 데이터프레임의 hadm_id 개수 확인
print(f"admissions hadm_id: {len(admissions['hadm_id'].unique())}")
print(f"average_amounts hadm_id: {len(average_amounts['hadm_id'].unique())}")
print(f"procedure_counts hadm_id: {len(procedure_counts['hadm_id'].unique())}")
print(f"average_values_chartevent hadm_id: {len(average_values_chartevent['hadm_id'].unique())}")
print(f"average_values_output hadm_id: {len(average_values_output['hadm_id'].unique())}")
print(f"icustays_aggregated hadm_id: {len(icustays_aggregated['hadm_id'].unique())}")

# 교집합 확인
common_hadm_ids = set(admissions['hadm_id'])
for df in [average_amounts, procedure_counts, average_values_chartevent, average_values_output, icustays_aggregated]:
    common_hadm_ids = common_hadm_ids.intersection(df['hadm_id'])

print(f"Total common hadm_ids across all datasets: {len(common_hadm_ids)}")

admissions hadm_id: 6478
average_amounts hadm_id: 2357
procedure_counts hadm_id: 2365
average_values_chartevent hadm_id: 2378
average_values_output hadm_id: 2247
icustays_aggregated hadm_id: 2378
Total common hadm_ids across all datasets: 2243